site_name: TM1py
site_description: Python client for TM1 REST API
repo_url: https://github.com/cubewise-code/tm1py

theme:
  name: material
  palette:
    - scheme: default
      primary: "blue"
      accent: "orange"
  features:
    - navigation.sections
    - search.suggest
    - search.highlight
    - content.code.copy

nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - API Reference:
      #- Core:
      #    - TM1Service: reference/tm1service.md
      - Services:
          - CubeService: reference/CubeService.md
          - DimensionService: reference/DimensionService.md
      - Objects:
          - Cube: reference/Cube.md
          - Dimension: reference/Dimension.md
      #- Utilities:
      #    - Utils: reference/utils.md

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: sphinx
            show_root_heading: true
            show_root_full_path: false
            show_source: true
  - gen-files:
      scripts:
        - docs/gen_ref_index.py

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/cubewise-code/tm1py
  version:
    provider: mike

extra_css:
  - stylesheets/extra.css

site_url: https://blog.onefloid.de/tm1py/
